apps/urls.py
from django.urls import path, include

from . import views


app_name = 'apps'

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/', views.posts, name="posts"),
    path('post/<int:post_id>/', views.post, name="post"),
    path('new_post/', views.new_post, name="new_post"),
    path('add_body/<int:post_id>/', views.add_body, name="add_body"),
    path('edit_body/<int:body_id>/', views.edit_body, name="edit_body"),
    path('delete_post/<int:post_id>/', views.delete_post, name="delete_post"),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('apps.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include

from . import views


app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"),
    path('user_profile/', views.user_profile, name="user_profile"),
   
]

apps/models.py
from django.db import models
from django.contrib.auth.models import User 


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    email = models.EmailField(max_length=50, null=True)
    bio = models.TextField(blank=True)
    photo = models.ImageField(upload_to='images/', blank=True, null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='', blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Body(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to='', blank=True)
    posted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

apps/forms.py
from django import forms
from django.forms import fields

from .models import Post, Body, Profile

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title']
        labels = {'text':''}

class BodyForm(forms.ModelForm):
    class Meta:
        model = Body
        fields = ['text']
        labels = {'text': 'body:'}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

users/forms.py
from django import forms 

from apps.models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'

apps/views.py
from django.http import request
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Post, Body, Profile
from .forms import PostForm, BodyForm


def home(request):
    return render(request, 'apps/home.html')

def posts(request):
    posts = Post.objects.order_by("posted_at")
    context = {'posts': posts}
    return render(request, 'apps/posts.html', context)

def post(request, post_id):
    post = Post.objects.get(id=post_id)
    
    bodies = post.body_set.order_by("posted_at")
    context = {'post': post, 'bodies': bodies}
    return render(request, 'apps/post.html', context)


def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('apps:posts')

    context = {'form': form}
    return render(request, 'apps/new_post.html', context)

def add_body(request, post_id):
    post = Post.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404


    if request.method != 'POST':
        form = BodyForm()
    else:
        form = BodyForm(data=request.POST)

        if form.is_valid():
            add_body = form.save(commit=False)
            add_body.post = post
            add_body.save()
            return redirect('apps:post', post_id=post_id)
    
    context = {'form': form, 'post': post}
    return render(request, 'apps/add_body.html', context)

def edit_body(request, body_id):
    body = Body.objects.get(id=body_id)
    post = body.post
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = BodyForm(instance=body)
    else:
        form = BodyForm(instance=body, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('apps:post', post_id=post.id)
    
    context = {'form': form, 'topic': post, 'body': body}
    return render(request, 'apps/edit_body.html', context)

def delete_post(request, post_id):
    post = Post.objects.get(id=post_id)
    if post.owner != request.user:
        raise Http404

    if request.method == 'POST':
        post.delete()
        return redirect('apps:posts')
    
    context = {'post': post}
    return render(request, 'apps/delete_post.html', context)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

from apps.models import Profile
from .forms import ProfileForm


def user_profile(request):
    profiles = Profile.objects.all()
    return render(request, 'registration/user_profile.html', {'profiles': profiles})

def edit_profile(request):
    profile = Profile.objects.all()
    
    if request.method == 'POST':
        form = ProfileForm(data=request.POST)
        if form.is_valid():
            form.save()
    else:
        form = ProfileForm() 
    
    return render (request, 'registration/edit_profile.html', {'form': form})


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('apps:home')
    
    context = {'form': form}
    return render(request, 'registration/register.html', context)

apps/templates/apps/add_body.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content %}
  
  <p><h4>Adding body:</h4></p>
  <form method="post" action="{% url 'apps:add_body' post.id %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-success">SAVE</button>

  </form>


{% endblock content%}

apps/templates/apps/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-light, initial-scale=1">

      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" 
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"/>

      <title>My App</title>
     
   </head>
   <body>
     
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container-fluid">
           <a class="navbar-brand" href="#">MyApp</a>
           <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'apps:home' %}">Home</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="{% url 'apps:posts' %}">Posts</a>
               </li>
             </ul>
             <ul class="navbar-nav ml-auto">
              <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="bi bi-person"></i>
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"/>
                      </svg>
                  {% if user.is_authenticated %}
                      Hello, {{ user.username }}
                    </a>
                  
                    <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarLightDropdownMenuLink">
                      <li><a class="dropdown-item" href="{% url 'users:user_profile' %}">Profile</a></li>
                      <li><a class="dropdown-item" href="{% url 'users:logout' %}">Sign out</a></li>
                    </ul>
                  {% else %}
                
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item"></li>
                      <a class="nav-link" href="{% url 'users:login' %}">Sign in</a>
                    </li>
              
                  {% endif %}
                  
                  </li>
                </ul>
              </div>
             </ul>
           </div>
         </div>
       </nav>
      
      
      <main role="main" class="container">
         <div class="pb-2 mb-2 border-bottom">
           {% block page_header %}{% endblock page_header %}
         </div>
         <div>
           {% block content %}{% endblock content %}
         </div>
      </main>

      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" 
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" 
      integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

   </body>
</html>

apps/templates/apps/delete_post.html
{% extends 'apps/base.html' %}

{% block content %}
  <p>Are you sure you want to delete {{ post }}?</p>
  <form method="post" action="{% url 'apps:delete_post' post.id %}">
      {% csrf_token %}
      {{ form.as_p }}

      <a href="{% url 'apps:posts' %}">Cancel</a>
      <button type="submit" class="btn btn-primary">Confirm</button>
  </form>

{% endblock content %}

apps/templates/apps/edit_body.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}
{% block content %}
  
  <p><h4>Editing body:</h4></p>
  <form method="post" action="{% url 'apps:edit_body' body.id %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit" class="btn btn-success">SAVE</button>

  </form>


{% endblock content%}

apps/templates/apps/home.html
{% extends 'apps/base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
  <body>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
    <h3>Welcome to my site.</h3>
  <p>
  <small>I'm <strong>Allan</strong> and i would like to be your friend.</small>
  </p>

  </body>
</html>

{% endblock content %}

apps/templates/apps/new_post.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}
{% block content%}
   <form method="post" action="{% url 'apps:new_post' %}">
     {% csrf_token %}
     {{ form.as_p }}

     <button type="submit" class="btn btn-primary">ADD</button>
   </form>
{% endblock content %}

apps/templates/apps/post.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}

{% block content%}
  <p><h3>Post:</h3></p>
  <p><a href="{% url 'apps:post' post.id %}">{{ post }}</a></p>
  {% if user.is_authenticated %}
    <p><a href="{% url 'apps:add_body' post.id %}">Add body</a></p>
    <p><a href="{% url 'apps:delete_post' post.id %}">Delete Post</a></p>
    
    <ul>
    {% for body in bodies %}
      <p><a href="{% url 'apps:edit_body' body.id %}">Edit text</a>
      <li>{{ body.posted_at|date:'M d, Y H:i' }}</li> 
      <li>{{ body.text|linebreaks }}</li>
    {% empty %}
      <li>No posts yet.</li>
    {% endfor %}
    </ul>

  {% else %}

    <ul>
    {% for body in bodies %}
      <li>{{ body.posted_at|date:'M d, Y H:i' }}</li> 
      <li>{{ body.text|linebreaks }}</li>
    {% empty %}
      <li>No posts yet.</li>
    {% endfor %}
    </ul>
  {% endif %}

{% endblock content %}

apps/templates/apps/posts.html
{% extends 'apps/base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block content%}
<body>
  <link type="text/css" rel="stylesheet" href="{% static 'css/posts.css' %}"/>

    {% if user.is_authenticated %}
      <p><a href="{% url 'apps:new_post' %}">Add Post</a></p>

    <div class="content">
        <ul>
        {% for post in posts %}
        <div class="row justify-content-center">
          <div class="col-lg-4 col-sm-6 mb-4">
            <div class="card h-100">
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'apps:post' post.id %}">{{ post }}</a>
                </h4>
                <p class="card-text">{{ post.posted_at }}</p>
              </div>
            </div>
          </div>
          
        {% empty %}
          <li>No posts yet.</li>
        {% endfor %}
        </ul>
    {% else %}
        <ul>
        {% for post in posts %}
        <div class="row justify-content-center">
          <div class="col-lg-4 col-sm-6 mb-4">
            <div class="card h-100">
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{% url 'apps:post' post.id %}">{{ post }}</a>
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur eum quasi sapiente nesciunt? Voluptatibus sit, repellat sequi itaque deserunt, dolores in, nesciunt, illum tempora ex quae? Nihil, dolorem!</p>
              </div>
            </div>
          </div>
        </div>  
          
        
        {% empty %}
          <li>No posts yet.</li>
        {% endfor %}
        </ul>
  
    </div>
    {% endif %}
</body>
{% endblock content %}